<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Webpage</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> <!-- Add Google Material Icons CSS link -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.10.0/main.css"> <!-- Add FullCalendar CSS link -->
    <style>
        /* Styling for the body and header */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0; /* Background color for the body */
        }

        header {
            background-color: #fff; /* Header background color */
            color: #333; /* Header text color */
            padding: 10px;
            text-align: right;
            border-bottom: 2px solid #000; /* Black stroke */
        }

        /* Styling for the navigation bar */
        .sidebar {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #fff; /* Navigation background color */
            padding-top: 20px;
            border-right: 2px solid #000; /* Black stroke */
        }

        .sidebar a {
            padding: 10px 15px;
            text-decoration: none;
            font-size: 18px;
            color: #333; /* Navigation text color */
            display: block;
            transition: 0.3s;
        }

        .sidebar a:hover {
            background-color: #eee; /* Hover background color */
        }

        /* Styling for the logo */
        .logo {
            text-align: center;
            padding: 10px;
        }

        /* Styling for the account and notification signs */
        .header-icons {
            display: inline-block;
            margin-right: 20px;
            font-size: 24px; /* Increase icon size */
        }

        /* Style the notification badge */
        .badge {
            background-color: red;
            color: white;
            padding: 5px 10px;
            border-radius: 50%;
            position: relative;
            top: -10px;
            left: -10px;
        }
         /* Styling for the main content */
         .calendar {
            max-width: 100%;
            margin: 0 auto;
            border: 1px solid #ddd;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .calendar-header {
            background-color: #007bff;
            color: #fff;
            text-align: center;
            padding: 10px;
        }

        .calendar-table {
            width: 100%;
            border-collapse: collapse;
        }

        .calendar-table th,
        .calendar-table td {
            text-align: center;
            padding: 10px;
            border: 1px solid #ddd;
        }

        .calendar-table th {
            background-color: #f0f0f0;
        }

        .calendar-table td {
            cursor: pointer;
        }

        .today {
            background-color: #007bff;
            color: #fff;
        }

        /* Responsive styles (same as before) */
        @media (max-width: 768px) {
            .calendar {
                font-size: 14px;
            }

            .calendar-table th,
            .calendar-table td {
                padding: 8px;
            }

            .calendar-header {
                font-size: 18px;
            }
        }
    </style>
</head>
<body>
    <header>
        <div class="header-icons">
            <a href="#"><i class="material-icons">account_circle</i></a> <!-- Google Material Icon for account -->
        </div>
        <div class="header-icons">
            <a href="#"><i class="material-icons">notifications</i><span class="badge">3</span></a> <!-- Google Material Icon for notification -->
        </div>
    </header>

    <div class="sidebar">
        <div class="logo">
            <img src="your-logo.png" alt="Logo" width="150">
        </div>
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Services</a>
        <a href="#">Contact</a>
    </div>

    <!-- Your webpage content goes here -->
    <div class="calendar">
        <div class="calendar-header">
            <h2 id="currentMonthYear"></h2>
        </div>
        <table class="calendar-table" id="calendarTable">
            <!-- Calendar content will be generated by JavaScript -->
        </table>
    </div>

    <script>
        function updateCalendar() {
            const currentDate = new Date();
            const currentYear = currentDate.getFullYear();
            const currentMonth = currentDate.getMonth();
            const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();

            const calendarHeader = document.getElementById("currentMonthYear");
            calendarHeader.textContent = currentDate.toLocaleString('default', { month: 'long', year: 'numeric' });

            const calendarTable = document.getElementById("calendarTable");
            calendarTable.innerHTML = "";

            for (let day = 1; day <= daysInMonth; day++) {
                const cell = document.createElement("td");
                cell.textContent = day;

                if (currentDate.getDate() === day) {
                    cell.classList.add("today");
                }

                calendarTable.appendChild(cell);

                if (new Date(currentYear, currentMonth, day).getDay() === 6) {
                    const newRow = document.createElement("tr");
                    calendarTable.appendChild(newRow);
                }
            }
        }

        updateCalendar(); // Initial update
    </script>
</body>
</html>
